USE [master]
GO

/****** Object:  Database [db_music]    Script Date: 2/21/2025 5:32:05 PM ******/
CREATE DATABASE [db_music]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_music', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\db_music.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_music_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\db_music_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_music].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_music] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_music] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_music] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_music] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_music] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_music] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [db_music] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_music] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_music] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_music] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_music] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_music] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_music] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_music] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_music] SET  DISABLE_BROKER 
GO

ALTER DATABASE [db_music] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_music] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_music] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_music] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_music] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_music] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_music] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_music] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [db_music] SET  MULTI_USER 
GO

ALTER DATABASE [db_music] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_music] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_music] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_music] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [db_music] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [db_music] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [db_music] SET QUERY_STORE = ON
GO

ALTER DATABASE [db_music] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [db_music] SET  READ_WRITE 
GO

